name: Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Укажите версию'
        required: true
      prerelease:
        description: 'Пометить как pre-release?'
        type: boolean
        default: false

jobs:
  build-release:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: SteadyState.MainProject.WPF

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Compute versions
        id: ver
        shell: pwsh
        run: |
          $TAG  = "${{ github.event.inputs.version }}"
          $ASM  = "$TAG.0"
          $YEAR = Get-Date -Format yyyy
          $DIR  = Join-Path $env:RUNNER_TEMP 'publish'

          "semver=$TAG"     >> $env:GITHUB_OUTPUT
          "asmver=$ASM"     >> $env:GITHUB_OUTPUT
          "year=$YEAR"      >> $env:GITHUB_OUTPUT
          "publishDir=$DIR" >> $env:GITHUB_OUTPUT

      - name: Publish via FolderProfile with version injection
        run: >
          dotnet publish SteadyState.MainProject.WPF.csproj
          -c Release
          /p:PublishProfile=FolderProfile
          /p:PublishDir=${{ steps.ver.outputs.publishDir }}
          /p:Version=${{ steps.ver.outputs.semver }}
          /p:AssemblyVersion=${{ steps.ver.outputs.semver }}
          /p:FileVersion=${{ steps.ver.outputs.semver }}
          /p:InformationalVersion=${{ steps.ver.outputs.semver }}
          /p:Copyright="Copyright © khramtsov.k ${{ steps.ver.outputs.year }}"

      - name: Locate EXE path
        id: out
        shell: pwsh
        run: |
          $outDir = '${{ steps.ver.outputs.publishDir }}'
          if (-not (Test-Path $outDir)) { throw "Publish dir not found: $outDir" }
          $exe = Get-ChildItem $outDir -Filter *.exe | Select-Object -First 1
          if (-not $exe) { throw "No .exe found in $outDir" }
          "exe=$($exe.FullName)" >> $env:GITHUB_OUTPUT
          Write-Host "EXE: $($exe.FullName)"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease }}
          commit: ${{ github.sha }}
          generateReleaseNotes: true
          makeLatest: ${{ inputs.prerelease && 'false' || 'true' }}
          artifacts: |
            ${{ steps.out.outputs.exe }}
